### ISSUE TITLE
En "Basique" et en "Aléatoire", quand l'utilisateur gagne, `fini` est incorrect

### ISSUE THREAD

**Issue by cmigliorini** [Achleole/IArthur#2]
... et le navigateur spamme le. serveur avec des `GET /puissance4/puissance4/ajax/waitForComputer`

(je n'ai pas encore réussi à gagner dans les autres modes 😛)
<img width="986" alt="image" src="https://user-images.githubusercontent.com/3218916/78470301-a6db2b80-7728-11ea-986e-de15b2c387a0.png">

**Comment by Achleole** [comment]
La fonciton updateGame dans app.js lancait waitForComputer tant que c'était a l'ordinateur de jouer, indépendanment de si la partie était finie ou pas.
